# データベース接続URL
spring.datasource.url=jdbc:h2:mem:testdb

# H2用のドライバーに変更
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Consoleを有効化（ブラウザで確認用）
spring.h2.console.enabled=true

# JPA（Hibernate）によるテーブル自動生成を有効化
spring.jpa.hibernate.ddl-auto=update

# テーブル生成後に data.sql を実行させる設定
spring.jpa.defer-datasource-initialization=true

# SQLログの表示（動作確認用・任意）
spring.jpa.show-sql=true