# H2 データベース接続設定
spring.datasource.url=jdbc:h2:mem:reviewerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console の有効化 (ブラウザで DB の中身を確認できるツール)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate 設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# data.sql (初期データ) を自動実行する設定
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always